# site settings

title: Rik Bose
description: AI/NLP Researcher
taglong: AI/NLP Researcher
tagshort: Jekyll theme
url: "https://rbose.dev"
baseurl: ""
permalink: pretty
repo: https://github.com/infiniterik/infiniterik.github.io

# author settings

author:
  name: Rik Bose
  email: rikbose.cs@gmail.com
photo: /assets/jpg/profile.jpg

# social media links

social:
  github: infiniterik
  linkedin: rikbose

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
