# site settings

title: Rik Bose
description: AI/NLP Researcher
taglong: Agentic AI
tagshort: "@infiniterik"
url: "https://infiniterik.github.io/"
baseurl: ""
permalink: pretty
repo: https://github.com/infiniterik/infiniterik.github.io

# author settings

author:
  name: Rik Bose
  email: rik.bose@jhuapl.edu
photo: /assets/jpg/profile.jpg

# social media links

social:
  github: infiniterik
  linkedin: rikbose
  bsky: infiniterik.bsky.social

# build settings

exclude:
  - LICENSE
  - README.md

collections:
  papers:
    output: true
    permalink: /:collection/:categories:output_ext

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
